# Generated by Django 4.2.4 on 2023-11-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_coin_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="transaction", name="portfolio",),
    ]
