# Generated by Django 4.2.5 on 2023-11-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_name_useraccount_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="portfolio",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.portfolio",
            ),
            preserve_default=False,
        ),
    ]
