# Generated by Django 4.2.5 on 2023-11-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_transaction_portfolio"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="portfolio",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.portfolio",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
