# Generated by Django 4.2.5 on 2023-11-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_transaction_portfolio_alter_portfolio_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction", old_name="portfolio", new_name="portfolioId",
        ),
    ]
